### PR TITLE
Local caching of state and unsent statements

### PR DESCRIPTION
**Pull request by ryanrolds**
This is not finished, but I figured it would be good to get some eye on it.

I hit a sang, the way the xapiwrapper handles request errors needs some attention (https://github.com/adlnet/xAPIWrapper/issues/80). I will be working that issue next, once it's done and merged I will update this repos copy of the wrapper and finish up the error handling.

### CODE REVIEW

**Comment by jpablo128** [comment]
I'll wait then

**Comment by ryanrolds** [comment]
Pending https://github.com/adlnet/xAPIWrapper/pull/84.

While updating it to use error-first callbacks I noticed that changing users should invalidate/empty the cache. I will address this issue when that PR is done.

**Comment by ryanrolds** [comment]
I've updated the xAPI wrapper and for the most part completed the caching and a component for requiring the cache to be empty (sent) to be marked completed. This code is not in production yet, we are will be starting beta testing next week. Once beta testing is complete and any bugs fixed I will be more sure of these changes.

@jpablo128 If you have time, please review these changes and let me know if I deviated too much from your plans and I will try to realign things.

**Comment by jpablo128** [comment]
Thank you @ryanrolds . I'm hoping to have some time next week to review Adapt stuff, I've away from it for a while.

**Comment by jpablo128** [comment]
Hi @ryanrolds,  sorry it took me so long to get to this... It's a great addition and I want to merge it into master, but I'm seeing some issues when testing with the rustici and adlxapi (xapi-launch) launch methods (due to the use of 'registration', and some other stuff). I think the fixes are just a few little things here and there. I'm also finding some pre-existing bugs that I need to take care of. 
Instead of trying to explain, I think it's easier that I work on a separate branch to merge your PR, do the fixes etc. ... and then push that temporary branch here so you can see it before I merge everything into master (I guess I can add any explanations to the diffs if needed) , ... I want to avoid introducing changes that would break how things work on your side/situation...

**Comment by jpablo128** [comment]
Hi @ryanrolds I've added a branch  https://github.com/Acutilis/adapt-tkhub-xAPI/tree/apply-irisEd-cachePR  that incorporates PR #2  and tweaks it a bit so caching works with the harcoded, rustici, and spoor launch methods.

**Pull request merged**
